# Generated by Django 3.1.5 on 2021-01-20 01:06

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Python', max_length=50)),
                ('courseNum', models.IntegerField(help_text='Course Number', max_length=3)),
                ('instructName', models.CharField(help_text="Instructor's Name", max_length=50)),
                ('durationDays', models.IntegerField(help_text='Days to complete course', max_length=2)),
            ],
            managers=[
                ('djangoClassesManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
